name: DAST - OWASP ZAP Full Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4

      - name: Install lab dependencies
        working-directory: fastbank-auth-lab/src
        run: |
          npm install

      - name: Start vulnerable app
        working-directory: fastbank-auth-lab/src
        run: |
          npm start &
          # wait for the server to boot
          sleep 40
        
      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'http://localhost:3001'
          fail_action: true
          allow_issue_writing: false
